// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SciezkaPrawa.Infrastructure;

#nullable disable

namespace SciezkaPrawa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207012954_addNewFieldForAct")]
    partial class addNewFieldForAct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("SciezkaPrawa.Domain.Entities.Act", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AmendmentsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Committee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsultationEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsultationStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasConsultation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlainLanguageSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sponsor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("SciezkaPrawa.Domain.Entities.ActReadingVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Abstain")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ActId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Against")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("For")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReadingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.ToTable("ActReadingVotes");
                });

            modelBuilder.Entity("SciezkaPrawa.Domain.Entities.ActStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.ToTable("ActStages");
                });

            modelBuilder.Entity("SciezkaPrawa.Domain.Entities.ActTag", b =>
                {
                    b.Property<Guid>("ActId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ActTags");
                });

            modelBuilder.Entity("SciezkaPrawa.Domain.Entities.ActVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.ToTable("ActVersion");
                });

            modelBuilder.Entity("SciezkaPrawa.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SciezkaPrawa.Domain.Entities.ActReadingVote", b =>
                {
                    b.HasOne("SciezkaPrawa.Domain.Entities.Act", "Act")
                        .WithMany("ReadingVotes")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");
                });

            modelBuilder.Entity("SciezkaPrawa.Domain.Entities.ActStage", b =>
                {
                    b.HasOne("SciezkaPrawa.Domain.Entities.Act", "Act")
                        .WithMany("Stages")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");
                });

            modelBuilder.Entity("SciezkaPrawa.Domain.Entities.ActTag", b =>
                {
                    b.HasOne("SciezkaPrawa.Domain.Entities.Act", "Act")
                        .WithMany("Tags")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SciezkaPrawa.Domain.Entities.Tag", "Tag")
                        .WithMany("ActTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SciezkaPrawa.Domain.Entities.ActVersion", b =>
                {
                    b.HasOne("SciezkaPrawa.Domain.Entities.Act", "Act")
                        .WithMany("Versions")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");
                });

            modelBuilder.Entity("SciezkaPrawa.Domain.Entities.Act", b =>
                {
                    b.Navigation("ReadingVotes");

                    b.Navigation("Stages");

                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("SciezkaPrawa.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ActTags");
                });
#pragma warning restore 612, 618
        }
    }
}
